#!/bin/bash
# Test TrigCache accuracy and performance
# Run this on Pi5 to verify optimization benefits

echo "🧮 Testing TrigCache Performance & Accuracy"
echo "=========================================="
echo ""

# Check if running on Pi5
if grep -q "Raspberry Pi" /proc/cpuinfo 2>/dev/null; then
    echo "✅ Detected Raspberry Pi"
    echo "Model: $(cat /proc/device-tree/model 2>/dev/null || echo 'Unknown')"
else
    echo "ℹ️  Not running on Raspberry Pi (desktop mode)"
fi

echo ""
echo "📊 Browser Console Tests"
echo "------------------------"
echo "Open the game in Chromium/Firefox and paste these commands:"
echo ""
echo "// 1. Check if TrigCache is enabled"
echo "console.log('TrigCache status:', window.trigCache ? 'ENABLED ✅' : 'DISABLED ❌');"
echo ""
echo "// 2. Check FastMath mode"
echo "console.log('FastMath mode:', FastMath.getStats());"
echo ""
echo "// 3. Test accuracy (45° angle)"
echo "const testAngle = Math.PI / 4;"
echo "const nativeSin = Math.sin(testAngle);"
echo "const cacheSin = window.trigCache ? window.trigCache.sin(testAngle) : 'N/A';"
echo "console.log('Native sin(45°):', nativeSin);"
echo "console.log('Cache sin(45°):', cacheSin);"
echo "console.log('Error:', cacheSin !== 'N/A' ? Math.abs(nativeSin - cacheSin) : 'N/A');"
echo ""
echo "// 4. Performance benchmark (10,000 calls)"
echo "console.time('Native Math.sin');"
echo "for (let i = 0; i < 10000; i++) Math.sin(i * 0.01);"
echo "console.timeEnd('Native Math.sin');"
echo ""
echo "console.time('TrigCache.sin');"
echo "for (let i = 0; i < 10000; i++) window.trigCache.sin(i * 0.01);"
echo "console.timeEnd('TrigCache.sin');"
echo ""
echo "// 5. Check memory usage"
echo "console.log('TrigCache memory:', window.trigCache?.getStats());"
echo ""
echo "=========================================="
echo ""
echo "📈 Expected Results on Pi5:"
echo "  - TrigCache should be ENABLED"
echo "  - Sin accuracy error: < 0.0001"
echo "  - TrigCache.sin: 4-6x faster than Math.sin"
echo "  - Memory usage: ~3KB"
echo ""
echo "🎮 In-Game Performance:"
echo "  - Open game, play for 30 seconds"
echo "  - Check FPS with profileReport()"
echo "  - Should see 55-70 FPS (vs 30-40 FPS without optimizations)"
echo ""
